-- جدول الحضور والانصراف المرتبط مباشرة بحسابات Supabase Auth.
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  attendance_date date not null default current_date,
  check_in timestamptz,
  check_out timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, attendance_date)
);
